"""Update password model for encryption

Revision ID: 22a449a4c687
Revises: 2e60ce9d0a0e
Create Date: 2025-06-09 10:08:45.582827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a449a4c687'
down_revision = '2e60ce9d0a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encrypted_password', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('encryption_iv', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('encryption_key', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('encryption_key')
        batch_op.drop_column('encryption_iv')
        batch_op.drop_column('encrypted_password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
