"""Add password sharing functionality

Revision ID: 90c2c1f877e6
Revises: 22a449a4c687
Create Date: 2025-06-09 13:42:27.150635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c2c1f877e6'
down_revision = '22a449a4c687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['password_id'], ['passwords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_shares_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_shares_share_token'))

    op.drop_table('password_shares')
    # ### end Alembic commands ###
