"""Initial migration

Revision ID: a796bd9167fa
Revises: 
Create Date: 2025-06-11 09:09:14.237273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a796bd9167fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('encryption_iv', sa.Text(), nullable=False),
    sa.Column('encryption_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['password_id'], ['passwords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_shares_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_shares_share_token'))

    op.drop_table('password_shares')
    op.drop_table('passwords')
    op.drop_table('users')
    # ### end Alembic commands ###
